### ISSUE TITLE
[Bug]: Broken Patreon Link

### ISSUE THREAD

**Issue by creative-tutorials** [creative-tutorials/relatalk#6]
### Description

```shell
Patreon Link is broken, it does direct to the Patreon page. This error occurs in the Sidebar of the mobile view
```

### What browsers are you seeing the problem on?

Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codewithkin** [comment]
Please provide the link to your patreon so I can assist further
